kinobase/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movie.urls", namespace="movie")),
    path("users/", include("users.urls", namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from . import views

app_name = "movie"


urlpatterns = [
    path("",views.MovieListView.as_view(), name="movie_list"),
    path("film/<slug>", views.MovieDetailView.as_view(), name="movie_detail"),
    path("category/<slug>", views.MovieCategoryListView.as_view(), name="movie_category_list"),
    
    path("comment/delete/<int:comment_id>", views.comment_delete, name="comment_delete"),
    
    # FILTER AND SORTING 
    path("filter/<filter_by_what>/<filter_by>", views.MovieFilterView.as_view(), name="movie_filter"),
    path("sort/<str:sort_by>", views.MovieSortView.as_view(), name="movie_sort"),
    
    # SEARCH 
    path("search/", views.search, name="search")
]

users/urls.py
from django.urls import path ,reverse_lazy
from django.contrib.auth.views import *
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.custom_logout, name="logout"),
    path("register/", views.CustomRegisterView.as_view(), name="register"),
    
    path('password-reset/',PasswordResetView.as_view(
        template_name='auth/password_reset.html',
        html_email_template_name='auth/password_reset_email.html',
        email_template_name='auth/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset' ),
    
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html',
         ),name='password_reset_done'),
    
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    
      path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html',
        
         ),name='password_reset_complete'),
      
    
    
    # PROFILE 
    path("profile/", views.CustomUserProfileView.as_view(), name="profile"),
    
    path("profile/history/", views.ProfileHistoryView.as_view(), name="history"),
    path("profile/history/clear", views.ProfileClearHistoryView.as_view(), name="clear_history"),
    path("profile/favorites/clear", views.ProfileClearFavoritesView.as_view(), name="clear_favorites"),
    
    path("profile/favorites/", views.ProfileFavoritesView.as_view(), name="favorites"),
    path("profile/favorites/add/<int:movie_id>", views.AddToFavoritesView.as_view(), name="add_to_favorites"),
    
    
    path("profile/rating/add/<int:movie_id>/<int:rating_value>", views.AddRatingView.as_view(), name="add_rating"),
    path("profile/rating/delete/<int:rating_id>", views.DeleteRatingView.as_view(), name="delete_rating"),
    
    path("profile/rating-list", views.ProfileRatingListView.as_view(), name="rating_list"),
    path("profile/comment-list", views.CommentListView.as_view(), name="comment_list"),
    path("profile/comment/delete/<int:comment_id>", views.DeleteCommentView.as_view(), name="delete_comment"),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<!-- Mirrored from kinobase.org/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 13 Jan 2024 09:04:06 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->

<head>
  <meta charset="utf-8" />
  <meta name="color-scheme" content="dark" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="application-name" content="Кинобейс" />
  <title>Кинобейс</title>
  <meta name="keywords"
    content="Кинобейс, kinobase, смотреть фильмы онлайн, фильмы онлайн в хорошем качестве, кино смотреть онлайн, смотреть сериалы онлайн, сериалы онлайн в хорошем качестве, смотреть фильмы бесплатно, онлайн-кинотеатр" />
  <meta name="description"
    content="Смотрите бесплатно на сайте кинобейс - фильмы, сериалы и телепередачи в хорошем качестве" />
  <link rel="dns-prefetch" href="https://st.kinobase.org/" />
  <link rel="icon" href="../st.kinobase.org/favicon76d5.png?v=1705132301563" type="image/png" />
  <link rel="icon" href="https://st.kinobase.org/favicon.ico?v=1705132301563" type="image/x-icon" />
  {% if "film" in request.path %}
    <script src="{% static 'js/playerjs.js' %}" type="text/javascript"></script>
  {% endif %}
  <link rel="stylesheet" href="{% static 'css/style76d5.css' %}" type="text/css" />
</head>

<body class="dark">
  <script src="{% static 'js/jqueryae52.js' %}" defer></script>
  <script src="{% static 'js/bootae52.js' %}" defer></script>
  <script src="{% static 'js/master76d5.js' %}" defer></script>

  <div id="root" class="dark">
    <div id="header">
      <div class="container">
        <div id="logo">
          <a href="/" title="Кинобейс" alt="Кинобейс"><img src="{% static 'images/logo5e1f.png' %}" width="26" /></a>
        </div>

        <ul id="menu" class="nav nav-left">
          {% for cat in categories %}
          <li>
            <a href="{% url 'movie:movie_category_list' cat.slug %}">{{cat.name}}</a>
          </li>
          {% endfor %}
        </ul>

        <ul class="nav nav-right">
          <li id="slide">
            <a href="#"><svg height="18" width="18" class="icon" viewBox="2.5 3.5 11 9">
                <path fill-rule="evenodd"
                  d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
              </svg></a>
          </li>
          <li id="slide_close">
            <a href="#"><svg height="18" width="18" class="icon" viewBox="0 1 14 14">
                <path
                  d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
              </svg></a>
          </li>
          <li id="open_search">
            <a href="#"><svg height="18" width="18" class="icon" viewBox="0 0 16 16">
                <path
                  d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
              </svg></a>
          </li>

          <li id="settings" class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown"><svg height="18" width="18" class="icon"
                viewBox="0 0 16 16">
                <path
                  d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z" />
                <path
                  d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z" />
              </svg></a>
            {% if not request.user.is_authenticated %}
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <a href="{% url 'users:login' %}" class="" title="Войти">
                  Войти в профиль
                </a>
                <div class="links">
                  <p>
                    <a href="{% url 'users:password_reset' %}" class="">Я не помню пароль</a>
                  </p>
                  <p>
                    <a href="{% url 'users:register' %}" class="register">Зарегистрироваться</a>
                  </p>
                </div>
              </li>

              <li role="separator" class="divider"></li>
              <li>
                <button class="abtn player_settings" title="Настройки плеера">
                  Настройки плеера</button><span id="player_help" class="muted"></span>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <span class="muted" id="swdark">Темный</span>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" role="switch" id="theme_switch" />
                </div>
                <span class="muted" id="swlight">Светлый</span>
              </li>
            </ul>
            {% else %}
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <a href="{% url 'users:profile' %}"><svg height="15" width="15" class="icon" viewBox="0 0 16 16">
                    <path
                      d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z">
                    </path>
                  </svg>
                  Профиль</a>
              </li>
              <li>
                <a href="{% url 'users:favorites' %}"><svg height="15" width="15" class="icon" viewBox="0 0 16 16">
                    <path
                      d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z">
                    </path>
                  </svg>
                  Избранное</a>
              </li>
              <li>
                <a href="{% url 'users:history' %}"><svg height="15" width="15" class="icon" viewBox="0 0 16 16">
                    <path
                      d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022zm2.004.45a7 7 0 0 0-.985-.299l.219-.976q.576.129 1.126.342zm1.37.71a7 7 0 0 0-.439-.27l.493-.87a8 8 0 0 1 .979.654l-.615.789a7 7 0 0 0-.418-.302zm1.834 1.79a7 7 0 0 0-.653-.796l.724-.69q.406.429.747.91zm.744 1.352a7 7 0 0 0-.214-.468l.893-.45a8 8 0 0 1 .45 1.088l-.95.313a7 7 0 0 0-.179-.483m.53 2.507a7 7 0 0 0-.1-1.025l.985-.17q.1.58.116 1.17zm-.131 1.538q.05-.254.081-.51l.993.123a8 8 0 0 1-.23 1.155l-.964-.267q.069-.247.12-.501m-.952 2.379q.276-.436.486-.908l.914.405q-.24.54-.555 1.038zm-.964 1.205q.183-.183.35-.378l.758.653a8 8 0 0 1-.401.432z">
                    </path>
                    <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0z"></path>
                    <path
                      d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5">
                    </path>
                  </svg>
                  История</a>
              </li>
              <li>
                <a href="{% url 'users:rating_list' %}"><svg height="15" width="15" class="icon" viewBox="0 0 16 16">
                    <path
                      d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z">
                    </path>
                  </svg>
                  Оценки</a>
              </li>
              <li>
                <a href="{% url 'users:comment_list' %}"><svg height="15" width="15" class="icon" viewBox="0 0 16 16">
                    <path
                      d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105">
                    </path>
                  </svg>
                  Комментарии</a>
              </li>
              <li>
                <a href="{% url 'users:logout' %}" class="logout"><svg height="15" width="15" class="icon"
                    viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                      d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z">
                    </path>
                    <path fill-rule="evenodd"
                      d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z">
                    </path>
                  </svg>
                  Выйти</a>
              </li>

              <li role="separator" class="divider"></li>
              <li>
                <button class="abtn player_settings" title="Настройки плеера">
                  Настройки плеера</button><span id="player_help" class="muted">Новый, HLS</span>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <span class="muted" id="swdark">Темный</span>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" role="switch" id="theme_switch" checked="checked" />
                </div>
                <span class="muted" id="swlight">Светлый</span>
              </li>
            </ul>
            {% endif %}
          </li>
        </ul>

        <div id="header_search" class="nav-right">
          <form action="" method="get" id="search_form">
            <span id="search_back" title="Назад"></span>
            <input onkeyup="dynamicSearch(this.value)" type="text" name="query" placeholder="Поиск" value=""
              autocomplete="off" id="search_input" />
            <input type="submit" value="" id="search_btn" />

            <div  class="autocomplete-suggestions"
            style="position: absolute; max-height: 900px; z-index: 9999; width: 881px; display: none;">
          </div>
          </form>
        </div>

        <div id="slide_menu">
          <ul>
            <li><a href="films.html">Фильмы</a></li>
            <li><a href="serials.html">Сериалы</a></li>
            <li><a href="tv.html">Телепередачи</a></li>
            <li><a href="animation.html">Мультфильмы</a></li>
            <li><a href="soon.html">Скоро</a></li>
            <li><a href="collections.html">Подборки</a></li>
          </ul>
        </div>
      </div>
    </div>
    <style>
      .message {
        padding: 10px 15px;
        background-color: aliceblue;
        color: #000000;
        border-radius: 5px;
        z-index: 999;
        position: absolute;
        right: 5%;

      }
    </style>

    {% if messages %}
    <span class="message">
      {% for message in messages %}
      {{ message }}
      {% endfor %}
    </span>
    <script>
      let msg = document.querySelector(".message");
      setInterval(() => {
        msg.style.display = "none"
      }, 3000)
    </script>
    {% endif %}
    {% block content %} {% endblock %}
    <div id="footer">
      <p>Пишите нам на почту: <a href="#" id="footer_mail"></a></p>
    </div>
  </div>
  <script src="{% static 'js/search.js' %}"></script>
</body>

</html>

templates/favorites.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <div id="main">
            <div class="container">




                <div id="filters_row" class="row">
                    <div class="left">
                        <h1>Избранное</h1>
                    </div>
                    <div class="right">
                        <a href="{% url 'users:clear_favorites' %}" class="abtn" title="Очистить историю просмотров" alt="Очистить историю просмотров" id="clear_history">
                            Очистить
                        </a>
                    </div>
                </div>


                <ul class="items with_spacer">
                    {% for movie in object_list %}
                    <li class="item">
                        <div class="poster">
                        <a href="{% url 'movie:movie_detail' movie.slug %}"
                            ><img
                            src="{{movie.cover.url}}"
                            class="img-responsive"
                            loading="lazy"
                            alt="{{movie.title}}"
                            title="{{movie.title}}"
                            width="242"
                            height="358" /></a
                        ><button
                            class="favorite"
                            data-movie-id="223525"
                            title="Добавить в избранное"
                        ></button>
                        </div>
                        <div class="title">
                        <a
                            href="{% url 'movie:movie_detail' movie.slug %}"
                            alt="{{movie.title}}"
                            title="{{movie.title}}"
                            >{{movie.title}}</a
                        >
                        </div>
                        <span class="rating">{{movie.get_average_rating}}</span
                        ><span class="year">{{movie.year}}, {{movie.quality}}</span>
                    </li>
                    {% empty %}
                    <p>В истории ничего нет </p>
                  {% endfor %}
                </ul>
                <center>
                    <div id="pg_full">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    Предыдущая
                                </a>
                                </li>
                            {% endif %}
                 
                            {% for p in page_obj.paginator.page_range|slice:"10" %}
                                
                                {% if p == page_obj.number %}
                                <li class="active">
                                    <a href="?page={{ p }}">{{ p }}</a>
                                </li>
                                {% else %}
                                <li>
                                    <a href="?page={{ p }}">{{ p }}</a>
                                </li>
                                {% endif %}
                                
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}" class="next">
                                        Следующая
                                    </a>
                                </li>
                                <li>
                                 <a href="?page={{ page_obj.paginator.num_pages }}">
                                    {{ page_obj.paginator.num_pages }}
                                </a> 
                                </li>
                              
                            {% endif %}
                        </ul>
                    </div>
                </center>
                <center>
                    <div id="pg_small">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    Предыдущая
                                </a>
                                </li>
                            {% endif %}
                            <li>
                                <select action="{{ request.path }}?" method="get">
                                    <option value="1" selected="selected">
                                        1 / {{ page_obj.paginator.num_pages }}
                                    </option>
                                    {% for p in page_obj.paginator.page_range|slice:"10" %}
                                
                                    <option value="{{ p }}">{{ p }}</option>

                                    {% endfor %}

                                    <option value="{{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</option>
                                </select>
                            </li>
                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}" class="next">
                                    Следующая
                                </a>
                            </li>
                            <li>
                             <a href="?page={{ page_obj.paginator.num_pages }}">
                                {{ page_obj.paginator.num_pages }}
                            </a> 
                            </li>
                          
                        {% endif %}
                        </ul>
                </center>


           



            </div>
        </div>
{% endblock %}

templates/history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <div id="main">
            <div class="container">




                <div id="filters_row" class="row">
                    <div class="left">
                        <h1>Просмотры</h1>
                    </div>
                    <div class="right">
                        <a href="{% url 'users:clear_history' %}" class="abtn" title="Очистить историю просмотров" alt="Очистить историю просмотров" id="clear_history">
                            Очистить
                        </a>
                    </div>
                </div>


                <ul class="items with_spacer">
                    {% for movie in object_list %}
                    <li class="item">
                        <div class="poster">
                        <a href="{% url 'movie:movie_detail' movie.slug %}"
                            ><img
                            src="{{movie.cover.url}}"
                            class="img-responsive"
                            loading="lazy"
                            alt="{{movie.title}}"
                            title="{{movie.title}}"
                            width="242"
                            height="358" /></a
                        ><button
                            class="favorite"
                            data-movie-id="223525"
                            title="Добавить в избранное"
                        ></button>
                        </div>
                        <div class="title">
                        <a
                            href="{% url 'movie:movie_detail' movie.slug %}"
                            alt="{{movie.title}}"
                            title="{{movie.title}}"
                            >{{movie.title}}</a
                        >
                        </div>
                        {{movie.get_average_rating}}<span class="year">{{movie.year}}, {{movie.quality}}</span>
                    </li>
                    {% empty %}
                    <p>В истории ничего нет </p>
                  {% endfor %}
                </ul>
                <center>
                    <div id="pg_full">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    Предыдущая
                                </a>
                                </li>
                            {% endif %}
                 
                            {% for p in page_obj.paginator.page_range|slice:"10" %}
                                
                                {% if p == page_obj.number %}
                                <li class="active">
                                    <a href="?page={{ p }}">{{ p }}</a>
                                </li>
                                {% else %}
                                <li>
                                    <a href="?page={{ p }}">{{ p }}</a>
                                </li>
                                {% endif %}
                                
                            {% endfor %}
                            
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}" class="next">
                                        Следующая
                                    </a>
                                </li>
                                <li>
                                 <a href="?page={{ page_obj.paginator.num_pages }}">
                                    {{ page_obj.paginator.num_pages }}
                                </a> 
                                </li>
                              
                            {% endif %}
                        </ul>
                    </div>
                </center>
                <center>
                    <div id="pg_small">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    Предыдущая
                                </a>
                                </li>
                            {% endif %}
                            <li>
                                <select action="{{ request.path }}?" method="get">
                                    <option value="1" selected="selected">
                                        1 / {{ page_obj.paginator.num_pages }}
                                    </option>
                                    {% for p in page_obj.paginator.page_range|slice:"10" %}
                                
                                    <option value="{{ p }}">{{ p }}</option>

                                    {% endfor %}

                                    <option value="{{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</option>
                                </select>
                            </li>
                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}" class="next">
                                    Следующая
                                </a>
                            </li>
                            <li>
                             <a href="?page={{ page_obj.paginator.num_pages }}">
                                {{ page_obj.paginator.num_pages }}
                            </a> 
                            </li>
                          
                        {% endif %}
                        </ul>
                </center>


           



            </div>
        </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div id="main">
        <div class="container">
          <div id="index_page">
            <h2><a href="/">Фильмы</a></h2>

            <ul class="items">
                {% for movie in object_list %}
                <li class="item">
                    <div class="poster">
                    <a href="{% url 'movie:movie_detail' movie.slug %}"
                        ><img
                        src="{{movie.cover.url}}"
                        class="img-responsive"
                        loading="lazy"
                        alt="{{movie.title}}"
                        title="{{movie.title}}"
                        width="242"
                        height="358" /></a
                    >
                    <a
                        class="{% if movie in request.user.profile.favorites.all %}favorite is_favorited{% else %}favorite{% endif %}"
                        href="{% url 'users:add_to_favorites' movie.id %}"
                        title="Добавить в избранное"
                    ></a>
                    </div>
                    <div class="title">
                    <a
                        href="{% url 'movie:movie_detail' movie.slug %}"
                        alt="{{movie.title}}"
                        title="{{movie.title}}"
                        >{{movie.title}}</a
                    >
                    </div>
                    <span class="rating">{{movie.get_average_rating}}</span
                    ><span class="year">{{movie.year}}, {{movie.quality}}</span>
                </li>
              {% endfor %}
            </ul>

          </div>
        </div>
      </div>
{% endblock %}
    